name: bilancio_me
description: BilancioMe - Personal finance manager
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_iconpicker: ^3.2.4
  flutter_riverpod: ^2.4.0
  flutter_animate: ^4.2.0
  flex_color_picker: ^3.4.0
  fluentui_system_icons: ^1.1.0
  intl: ^0.20.2
  collection: ^1.17.0
  rxdart: ^0.27.0
  fl_chart: ^0.65.0
  uuid: ^4.0.0
  # Database locale
  sqflite: ^2.3.0
  path: ^1.8.3
  # Backup cloud
  file_picker:
  path_provider: ^2.1.1
  # Per export/import
  csv: ^5.1.1
  json_annotation: ^4.8.1
  # Sincronizzazione cloud
  share_plus: ^7.2.1
  open_file: ^3.3.2
  # Per OneDrive/Google Drive
  url_launcher: ^6.2.1
  # Per gestione file cloud
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  # Icone launcher
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
flutter:
  uses-material-design: true
  assets:
    - assets/creditCard.jpg
    - assets/chip.jpg
    - assets/logo.png

# Configurazione icone launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A174E"
  adaptive_icon_foreground: "assets/logo.png"
 