import 'package:flutter/material.dart';

class Category {
  String id;
  String name;
  IconData icon;
  String colorHex;
  String type; // income | expense
  bool isSeed;

  Category({
    required this.id,
    required this.name,
    required this.icon,
    required this.colorHex,
    required this.type,
    this.isSeed = false,
  });

  // Per compatibilità con serializzazione JSON
  int get iconCodePoint => icon.codePoint;

  Color get color => Color(int.parse(colorHex.replaceFirst('#', '0xff')));

  // Helper function to map code points to constant IconData instances
  static IconData _getIconFromCodePoint(int codePoint) {
    // Map of common Material Icons code points to their constant instances
    const iconMap = {
      0xe3c3: Icons.work,
      0xe8b8: Icons.card_giftcard,
      0xe3c4: Icons.shopping_cart,
      0xe56c: Icons.restaurant,
      0xe88a: Icons.home,
      0xe531: Icons.directions_car,
      0xe80c: Icons.school,
      0xe3c5: Icons.sports_esports,
      0xe8b9: Icons.attach_money,
      0xe91d: Icons.pets,
      0xe548: Icons.local_hospital,
      0xe539: Icons.flight,
      0xe0cd: Icons.phone,
      0xe30a: Icons.computer,
      0xe333: Icons.movie,
      0xe534: Icons.local_cafe,
      0xe540: Icons.local_bar,
      0xe43a: Icons.fitness_center,
      0xe1b7: Icons.child_care,
      0xe533: Icons.local_grocery_store,
      0xe89e: Icons.local_offer,
      0xe3ca: Icons.beach_access,
      0xe02f: Icons.book,
      0xe405: Icons.music_note,
      0xe8b7: Icons.savings,
      0xe59c: Icons.shopping_bag,
      0xe8b0: Icons.receipt,
      0xe4f4: Icons.spa,
      0xe3e3: Icons.healing,
      0xe3c5: Icons.park,
      0xe3c6: Icons.sports_soccer,
      0xe3c7: Icons.sports_basketball,
      0xe3c8: Icons.sports_tennis,
      0xe3c9: Icons.sports_golf,
      0xe3ca: Icons.sports_motorsports,
      0xe3cb: Icons.sports_bar,
      0xe3cc: Icons.sports_handball,
      0xe3cd: Icons.sports_volleyball,
      0xe3ce: Icons.sports_football,
      0xe3cf: Icons.sports_rugby,
      0xe3d0: Icons.sports_cricket,
      0xe3d1: Icons.sports_baseball,
      0xe3d2: Icons.sports_hockey,
      0xe3d3: Icons.sports,
      0xe3d4: Icons.fastfood,
      0xe3d5: Icons.icecream,
      0xe3d6: Icons.cake,
      0xe3d7: Icons.local_pizza,
      0xe3d8: Icons.local_dining,
      0xe3d9: Icons.emoji_food_beverage,
      0xe3da: Icons.emoji_nature,
      0xe3db: Icons.emoji_objects,
      0xe3dc: Icons.emoji_people,
      0xe3dd: Icons.emoji_transportation,
      0xe3de: Icons.emoji_events,
      0xe3df: Icons.emoji_symbols,
      0xe3e0: Icons.emoji_flags,
      0xe3e1: Icons.family_restroom,
      0xe3e2: Icons.group,
      0xe3e3: Icons.groups,
      0xe3e4: Icons.person,
      0xe3e5: Icons.person_outline,
      0xe3e6: Icons.people,
      0xe3e7: Icons.pregnant_woman,
      0xe3e8: Icons.child_friendly,
      0xe3e9: Icons.baby_changing_station,
      0xe3ea: Icons.elderly,
      0xe3eb: Icons.wc,
      0xe3ec: Icons.directions_bike,
      0xe3ed: Icons.directions_boat,
      0xe3ee: Icons.directions_bus,
      0xe3ef: Icons.directions_railway,
      0xe3f0: Icons.directions_subway,
      0xe3f1: Icons.directions_transit,
      0xe3f2: Icons.directions_walk,
      0xe3f3: Icons.electric_bike,
      0xe3f4: Icons.electric_car,
      0xe3f5: Icons.electric_moped,
      0xe3f6: Icons.electric_rickshaw,
      0xe3f7: Icons.electric_scooter,
      0xe3f8: Icons.train,
      0xe3f9: Icons.airplanemode_active,
      0xe3fa: Icons.airport_shuttle,
      0xe3fb: Icons.motorcycle,
      0xe3fc: Icons.car_rental,
      0xe3fd: Icons.car_repair,
      0xe3fe: Icons.local_taxi,
      0xe3ff: Icons.local_shipping,
      0xe400: Icons.two_wheeler,
      0xe401: Icons.pedal_bike,
      0xe402: Icons.moped,
      0xe403: Icons.subway,
      0xe404: Icons.tram,
      0xe405: Icons.directions_ferry,
      0xe406: Icons.directions_boat_filled,
      0xe407: Icons.sailing,
      0xe408: Icons.anchor,
      0xe409: Icons.house,
      0xe40a: Icons.apartment,
      0xe40b: Icons.business,
      0xe40c: Icons.cottage,
      0xe40d: Icons.villa,
      0xe40e: Icons.cabin,
      0xe40f: Icons.holiday_village,
      0xe410: Icons.domain,
      0xe411: Icons.location_city,
      0xe412: Icons.location_on,
      0xe413: Icons.place,
      0xe414: Icons.public,
      0xe415: Icons.park,
      0xe416: Icons.terrain,
      0xe417: Icons.forest,
      0xe418: Icons.nature_people,
      0xe419: Icons.nature,
      0xe41a: Icons.eco,
      0xe41b: Icons.wb_sunny,
      0xe41c: Icons.nights_stay,
      0xe41d: Icons.brightness_2,
      0xe41e: Icons.brightness_3,
      0xe41f: Icons.brightness_4,
      0xe420: Icons.brightness_5,
      0xe421: Icons.brightness_6,
      0xe422: Icons.brightness_7,
      0xe423: Icons.star,
      0xe424: Icons.star_border,
      0xe425: Icons.star_half,
      0xe426: Icons.star_outline,
      0xe427: Icons.favorite,
      0xe428: Icons.favorite_border,
      0xe429: Icons.thumb_up,
      0xe42a: Icons.thumb_down,
      0xe42b: Icons.check_circle,
      0xe42c: Icons.cancel,
      0xe42d: Icons.block,
      0xe42e: Icons.warning,
      0xe42f: Icons.error,
      0xe430: Icons.info,
      0xe431: Icons.help,
      0xe432: Icons.lightbulb,
      0xe433: Icons.lightbulb_outline,
      0xe434: Icons.flash_on,
      0xe435: Icons.flash_off,
      0xe436: Icons.bolt,
      0xe437: Icons.battery_full,
      0xe438: Icons.battery_charging_full,
      0xe439: Icons.battery_alert,
      0xe43a: Icons.battery_unknown,
      0xe43b: Icons.battery_std,
      0xe43c: Icons.battery_saver,
      0xe43d: Icons.battery_4_bar,
      0xe43e: Icons.battery_5_bar,
      0xe43f: Icons.battery_6_bar,
      0xe440: Icons.battery_0_bar,
      0xe441: Icons.battery_1_bar,
      0xe442: Icons.battery_2_bar,
      0xe443: Icons.battery_3_bar,
      0xe8b8: Icons.account_balance,
      0xe8b9: Icons.trending_up,
      0xe8ba: Icons.checkroom,
      0xe8bb: Icons.cleaning_services,
      0xe8bc: Icons.local_gas_station,
      0xe8bd: Icons.more_horiz,
      0xe8be: Icons.category_outlined,
      0xe8bf: Icons.credit_card,
      0xe8c0: Icons.credit_card_outlined,
      0xe8c1: Icons.swap_horiz,
      0xe8c2: Icons.attach_money,
    };

    // Return the constant icon if found, otherwise create a fallback
    return iconMap[codePoint] ?? Icons.category_outlined;
  }

  // Costruttore da JSON per compatibilità
  Category.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        name = json['name'],
        icon = _getIconFromCodePoint(json['iconCodePoint']),
        colorHex = json['colorHex'],
        type = json['type'],
        isSeed =
            (json['isSeed'] is bool) ? json['isSeed'] : (json['isSeed'] == 1);

  // Metodo per serializzazione JSON
  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'iconCodePoint': icon.codePoint,
        'colorHex': colorHex,
        'type': type,
        'isSeed': isSeed ? 1 : 0, // <-- serializza come int
      };
}
